export const AllStates = [
    { "state_id": "42", "state_name": "Badakhshan", "country_id": "1" },
    { "state_id": "43", "state_name": "Badgis", "country_id": "1" },
    { "state_id": "44", "state_name": "Baglan", "country_id": "1" },
    { "state_id": "45", "state_name": "Balkh", "country_id": "1" },
    { "state_id": "46", "state_name": "Bamiyan", "country_id": "1" },
    { "state_id": "47", "state_name": "Farah", "country_id": "1" },
    { "state_id": "48", "state_name": "Faryab", "country_id": "1" },
    { "state_id": "49", "state_name": "Gawr", "country_id": "1" },
    { "state_id": "50", "state_name": "Gazni", "country_id": "1" },
    { "state_id": "51", "state_name": "Herat", "country_id": "1" },
    { "state_id": "52", "state_name": "Hilmand", "country_id": "1" },
    { "state_id": "53", "state_name": "Jawzjan", "country_id": "1" },
    { "state_id": "54", "state_name": "Kabul", "country_id": "1" },
    { "state_id": "55", "state_name": "Kapisa", "country_id": "1" },
    { "state_id": "56", "state_name": "Khawst", "country_id": "1" },
    { "state_id": "57", "state_name": "Kunar", "country_id": "1" },
    { "state_id": "58", "state_name": "Lagman", "country_id": "1" },
    { "state_id": "59", "state_name": "Lawghar", "country_id": "1" },
    { "state_id": "60", "state_name": "Nangarhar", "country_id": "1" },
    { "state_id": "61", "state_name": "Nimruz", "country_id": "1" },
    { "state_id": "62", "state_name": "Nuristan", "country_id": "1" },
    { "state_id": "63", "state_name": "Paktika", "country_id": "1" },
    { "state_id": "64", "state_name": "Paktiya", "country_id": "1" },
    { "state_id": "65", "state_name": "Parwan", "country_id": "1" },
    { "state_id": "66", "state_name": "Qandahar", "country_id": "1" },
    { "state_id": "67", "state_name": "Qunduz", "country_id": "1" },
    { "state_id": "68", "state_name": "Samangan", "country_id": "1" },
    { "state_id": "69", "state_name": "Sar-e Pul", "country_id": "1" },
    { "state_id": "70", "state_name": "Takhar", "country_id": "1" },
    { "state_id": "71", "state_name": "Uruzgan", "country_id": "1" },
    { "state_id": "72", "state_name": "Wardag", "country_id": "1" },
    { "state_id": "73", "state_name": "Zabul", "country_id": "1" },
    { "state_id": "74", "state_name": "Berat", "country_id": "2" },
    { "state_id": "75", "state_name": "Bulqize", "country_id": "2" },
    { "state_id": "76", "state_name": "Delvine", "country_id": "2" },
    { "state_id": "77", "state_name": "Devoll", "country_id": "2" },
    { "state_id": "78", "state_name": "Dibre", "country_id": "2" },
    { "state_id": "79", "state_name": "Durres", "country_id": "2" },
    { "state_id": "80", "state_name": "Elbasan", "country_id": "2" },
    { "state_id": "81", "state_name": "Fier", "country_id": "2" },
    { "state_id": "82", "state_name": "Gjirokaster", "country_id": "2" },
    { "state_id": "83", "state_name": "Gramsh", "country_id": "2" },
    { "state_id": "84", "state_name": "Has", "country_id": "2" },
    { "state_id": "85", "state_name": "Kavaje", "country_id": "2" },
    { "state_id": "86", "state_name": "Kolonje", "country_id": "2" },
    { "state_id": "87", "state_name": "Korce", "country_id": "2" },
    { "state_id": "88", "state_name": "Kruje", "country_id": "2" },
    { "state_id": "89", "state_name": "Kucove", "country_id": "2" },
    { "state_id": "90", "state_name": "Kukes", "country_id": "2" },
    { "state_id": "91", "state_name": "Kurbin", "country_id": "2" },
    { "state_id": "92", "state_name": "Lezhe", "country_id": "2" },
    { "state_id": "93", "state_name": "Librazhd", "country_id": "2" },
    { "state_id": "94", "state_name": "Lushnje", "country_id": "2" },
    { "state_id": "95", "state_name": "Mallakaster", "country_id": "2" },
    { "state_id": "96", "state_name": "Malsi e Madhe", "country_id": "2" },
    { "state_id": "97", "state_name": "Mat", "country_id": "2" },
    { "state_id": "98", "state_name": "Mirdite", "country_id": "2" },
    { "state_id": "99", "state_name": "Peqin", "country_id": "2" },
    { "state_id": "100", "state_name": "Permet", "country_id": "2" },
    { "state_id": "101", "state_name": "Pogradec", "country_id": "2" },
    { "state_id": "102", "state_name": "Puke", "country_id": "2" },
    { "state_id": "103", "state_name": "Sarande", "country_id": "2" },
    { "state_id": "104", "state_name": "Shkoder", "country_id": "2" },
    { "state_id": "105", "state_name": "Skrapar", "country_id": "2" },
    { "state_id": "106", "state_name": "Tepelene", "country_id": "2" },
    { "state_id": "107", "state_name": "Tirane", "country_id": "2" },
    { "state_id": "108", "state_name": "Tropoje", "country_id": "2" },
    { "state_id": "109", "state_name": "Vlore", "country_id": "2" },
    { "state_id": "110", "state_name": "Ayn Daflah", "country_id": "3" },
    { "state_id": "111", "state_name": "Ayn Tamushanat", "country_id": "3" },
    { "state_id": "112", "state_name": "Adrar", "country_id": "3" },
    { "state_id": "113", "state_name": "Algiers", "country_id": "3" },
    { "state_id": "114", "state_name": "Annabah", "country_id": "3" },
    { "state_id": "115", "state_name": "Bashshar", "country_id": "3" },
    { "state_id": "116", "state_name": "Batnah", "country_id": "3" },
    { "state_id": "117", "state_name": "Bijayah", "country_id": "3" },
    { "state_id": "118", "state_name": "Biskrah", "country_id": "3" },
    { "state_id": "119", "state_name": "Blidah", "country_id": "3" },
    { "state_id": "120", "state_name": "Buirah", "country_id": "3" },
    { "state_id": "121", "state_name": "Bumardas", "country_id": "3" },
    { "state_id": "122", "state_name": "Burj Bu Arririj", "country_id": "3" },
    { "state_id": "123", "state_name": "Ghalizan", "country_id": "3" },
    { "state_id": "124", "state_name": "Ghardayah", "country_id": "3" },
    { "state_id": "125", "state_name": "Ilizi", "country_id": "3" },
    { "state_id": "126", "state_name": "Jijili", "country_id": "3" },
    { "state_id": "127", "state_name": "Jilfah", "country_id": "3" },
    { "state_id": "128", "state_name": "Khanshalah", "country_id": "3" },
    { "state_id": "129", "state_name": "Masilah", "country_id": "3" },
    { "state_id": "130", "state_name": "Midyah", "country_id": "3" },
    { "state_id": "131", "state_name": "Milah", "country_id": "3" },
    { "state_id": "132", "state_name": "Muaskar", "country_id": "3" },
    { "state_id": "133", "state_name": "Mustaghanam", "country_id": "3" },
    { "state_id": "134", "state_name": "Naama", "country_id": "3" },
    { "state_id": "135", "state_name": "Oran", "country_id": "3" },
    { "state_id": "136", "state_name": "Ouargla", "country_id": "3" },
    { "state_id": "137", "state_name": "Qalmah", "country_id": "3" },
    { "state_id": "138", "state_name": "Qustantinah", "country_id": "3" },
    { "state_id": "139", "state_name": "Sakikdah", "country_id": "3" },
    { "state_id": "140", "state_name": "Satif", "country_id": "3" },
    { "state_id": "141", "state_name": "Sayda'", "country_id": "3" },
    { "state_id": "142", "state_name": "Sidi ban-al-'Abbas", "country_id": "3" },
    { "state_id": "143", "state_name": "Suq Ahras", "country_id": "3" },
    { "state_id": "144", "state_name": "Tamanghasat", "country_id": "3" },
    { "state_id": "145", "state_name": "Tibazah", "country_id": "3" },
    { "state_id": "146", "state_name": "Tibissah", "country_id": "3" },
    { "state_id": "147", "state_name": "Tilimsan", "country_id": "3" },
    { "state_id": "148", "state_name": "Tinduf", "country_id": "3" },
    { "state_id": "149", "state_name": "Tisamsilt", "country_id": "3" },
    { "state_id": "150", "state_name": "Tiyarat", "country_id": "3" },
    { "state_id": "151", "state_name": "Tizi Wazu", "country_id": "3" },
    { "state_id": "152", "state_name": "Umm-al-Bawaghi", "country_id": "3" },
    { "state_id": "153", "state_name": "Wahran", "country_id": "3" },
    { "state_id": "154", "state_name": "Warqla", "country_id": "3" },
    { "state_id": "155", "state_name": "Wilaya d Alger", "country_id": "3" },
    { "state_id": "156", "state_name": "Wilaya de Bejaia", "country_id": "3" },
    { "state_id": "157", "state_name": "Wilaya de Constantine", "country_id": "3" },
    { "state_id": "158", "state_name": "al-Aghwat", "country_id": "3" },
    { "state_id": "159", "state_name": "al-Bayadh", "country_id": "3" },
    { "state_id": "160", "state_name": "al-Jaza'ir", "country_id": "3" },
    { "state_id": "161", "state_name": "al-Wad", "country_id": "3" },
    { "state_id": "162", "state_name": "ash-Shalif", "country_id": "3" },
    { "state_id": "163", "state_name": "at-Tarif", "country_id": "3" },
    { "state_id": "164", "state_name": "Eastern", "country_id": "4" },
    { "state_id": "165", "state_name": "Manu'a", "country_id": "4" },
    { "state_id": "166", "state_name": "Swains Island", "country_id": "4" },
    { "state_id": "167", "state_name": "Western", "country_id": "4" },
    { "state_id": "168", "state_name": "Andorra la Vella", "country_id": "5" },
    { "state_id": "169", "state_name": "Canillo", "country_id": "5" },
    { "state_id": "170", "state_name": "Encamp", "country_id": "5" },
    { "state_id": "171", "state_name": "La Massana", "country_id": "5" },
    { "state_id": "172", "state_name": "Les Escaldes", "country_id": "5" },
    { "state_id": "173", "state_name": "Ordino", "country_id": "5" },
    { "state_id": "174", "state_name": "Sant Julia de Loria", "country_id": "5" },
    { "state_id": "175", "state_name": "Bengo", "country_id": "6" },
    { "state_id": "176", "state_name": "Benguela", "country_id": "6" },
    { "state_id": "177", "state_name": "Bie", "country_id": "6" },
    { "state_id": "178", "state_name": "Cabinda", "country_id": "6" },
    { "state_id": "179", "state_name": "Cunene", "country_id": "6" },
    { "state_id": "180", "state_name": "Huambo", "country_id": "6" },
    { "state_id": "181", "state_name": "Huila", "country_id": "6" },
    { "state_id": "182", "state_name": "Kuando-Kubango", "country_id": "6" },
    { "state_id": "183", "state_name": "Kwanza Norte", "country_id": "6" },
    { "state_id": "184", "state_name": "Kwanza Sul", "country_id": "6" },
    { "state_id": "185", "state_name": "Luanda", "country_id": "6" },
    { "state_id": "186", "state_name": "Lunda Norte", "country_id": "6" },
    { "state_id": "187", "state_name": "Lunda Sul", "country_id": "6" },
    { "state_id": "188", "state_name": "Malanje", "country_id": "6" },
    { "state_id": "189", "state_name": "Moxico", "country_id": "6" },
    { "state_id": "190", "state_name": "Namibe", "country_id": "6" },
    { "state_id": "191", "state_name": "Uige", "country_id": "6" },
    { "state_id": "192", "state_name": "Zaire", "country_id": "6" },
    { "state_id": "193", "state_name": "Other Provinces", "country_id": "7" },
    { "state_id": "194", "state_name": "Sector claimed by Argentina\/Ch", "country_id": "8" },
    { "state_id": "195", "state_name": "Sector claimed by Argentina\/UK", "country_id": "8" },
    { "state_id": "196", "state_name": "Sector claimed by Australia", "country_id": "8" },
    { "state_id": "197", "state_name": "Sector claimed by France", "country_id": "8" },
    { "state_id": "198", "state_name": "Sector claimed by New Zealand", "country_id": "8" },
    { "state_id": "199", "state_name": "Sector claimed by Norway", "country_id": "8" },
    { "state_id": "200", "state_name": "Unclaimed Sector", "country_id": "8" }
]